//Leetcode 389 Find the Difference
//Given two strings s and t which consist of only lowercase letters.
//
//String t is generated by random shuffling string s and then add one more letter at a random position.
//
//Find the letter that was added in t.
//
//Example:
//
//Input:
//s = "abcd"
//t = "abcde"
//
//Output:
//e
//
//Explanation:
//'e' is the letter that was added.
class Solution{

   char FindDifference(string s,string t){
	char a = 0;
	for(tmp:s){
	     a^=tmp;
	}
	for(tmp:t){
	     a^=tmp;
	}
	return a;

   }
}
//---------------题解思路----------------------------------
//1.首先理解这道题是找出多加入的字母比如原串为abc  新增串为 aebc 
// 那么
//2.常规
